"""
Django settings for my_scada project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Секреты и локальные настройки — в my_scada/local_settings.py (в .gitignore, не коммитится)
# или в переменных окружения. Пример local_settings.py:
#   DB_PASSWORD = '...'
#   SECRET_KEY = '...'   # python -c "import secrets; print(secrets.token_urlsafe(50))"
#   DEBUG = True         # только дома
try:
    from . import local_settings as _local
except ImportError:
    _local = None


def _setting(name, default=None):
    return getattr(_local, name, os.environ.get(name, default))


# Старый ключ оставлен запасным, чтобы деплой не упал; на сервере задать новый в local_settings.
SECRET_KEY = _setting('SECRET_KEY', 'django-insecure-e-jbp#k622f!r3_o93-u(v!q@@!k@sy12=0blyr4#5mx=$e8f3')

DEBUG = str(_setting('DEBUG', False)).lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = ['scada.tldev.ru', 'i.tldev.ru', 'scada.fedorov.team',
                 'localhost', '127.0.0.1', '192.168.1.44', '192.168.2.200']


# Application definition

INSTALLED_APPS = [
    'new_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'scada',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework.authentication.SessionAuthentication',
),
# Всё API только для вошедших: иначе аноним мог слать команды устройствам (devmanage)
'DEFAULT_PERMISSION_CLASSES': (
    'rest_framework.permissions.IsAuthenticated',
),
}

ROOT_URLCONF = 'my_scada.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_scada.wsgi.application'


DB_PASSWORD = _setting('DB_PASSWORD', '')

# Хост БД: на сервере localhost, дома — MySQL в виртуалке Multipass
# (DB_HOST = '192.168.2.2' в local_settings.py или переменной окружения)
DB_HOST = _setting('DB_HOST', 'localhost')

# Текущие показания датчиков (scada/current.py). На сервере в Redis заняты базы 1, 5, 6, 7.
REDIS_URL = _setting('REDIS_URL', 'redis://localhost:6379/2')

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_scada',
        'USER': 'user',
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': '3306',
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [STATIC_DIR]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/scada_errors.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
        },
    },
}
