# Generated by Django 3.2.11 on 2022-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sensorId', models.IntegerField(blank=True, default=None, null=True, verbose_name='Датчик')),
                ('type', models.IntegerField(blank=True, default=None, null=True, verbose_name='тип данных')),
                ('data', models.IntegerField(blank=True, default=0, null=True, verbose_name='данные')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Помойка',
                'verbose_name_plural': 'Помойка',
                'ordering': ['-id'],
            },
        ),
    ]
