# Generated by Django 3.2.8 on 2022-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sensorId', models.IntegerField(blank=True, default=0, null=True, verbose_name='тип данных')),
                ('type', models.IntegerField(blank=True, default=0, null=True, verbose_name='тип данных')),
                ('data', models.IntegerField(blank=True, default=0, null=True, verbose_name='данные')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
