# Generated by Django 3.2.8 on 2022-01-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
    ]
