# Generated by Django 3.2.8 on 2022-01-03 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0002_rename_sensors_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
