# Generated by Django 3.2.11 on 2022-04-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0002_tmp2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tmp',
        ),
        migrations.DeleteModel(
            name='tmp2',
        ),
    ]
