# Generated by Django 3.2.11 on 2022-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0003_auto_20220429_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Помойка',
                'verbose_name_plural': 'Помойка',
                'ordering': ['-id'],
            },
        ),
    ]
