# Generated by Django 3.2.11 on 2022-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0004_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Прилетело'),
        ),
    ]
