# Generated by Django 3.2.11 on 2022-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0005_tmp_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='неизвестнвый датчик', max_length=150, verbose_name='Наименование')),
            ],
        ),
    ]
