# Generated by Django 3.2.11 on 2022-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0006_sensorlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorlist',
            options={'ordering': ['sort', 'title'], 'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AddField(
            model_name='sensorlist',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Включен'),
        ),
        migrations.AddField(
            model_name='sensorlist',
            name='sort',
            field=models.IntegerField(default=9999, verbose_name='Индекс Сортировки'),
        ),
    ]
