# Generated by Django 3.2.11 on 2022-04-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0007_auto_20220429_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensorId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scada.sensorlist'),
        ),
    ]
