# Generated by Django 3.2.11 on 2022-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0008_alter_sensor_sensorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='--', max_length=100, verbose_name='Наименование')),
                ('units', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Ед Измерения')),
                ('divider', models.IntegerField(default=1, verbose_name='Делитель')),
            ],
            options={
                'verbose_name': 'Вид измерения',
                'verbose_name_plural': 'Виды измерений',
                'ordering': ['title'],
            },
        ),
    ]
