# Generated by Django 3.2.11 on 2022-04-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0009_datatypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='sort',
            field=models.IntegerField(default=9999, verbose_name='Индекс Сортировки'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scada.datatypes'),
        ),
    ]
