# Generated by Django 3.2.11 on 2022-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0010_auto_20220430_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='subtitle',
            field=models.CharField(default='-', max_length=3, verbose_name='Имя в датчике'),
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
