# Generated by Django 3.2.11 on 2022-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0011_auto_20220510_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
