# Generated by Django 3.2.11 on 2022-05-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0012_tmp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='-', max_length=100, verbose_name='Наименование')),
                ('filename', models.CharField(default='-', max_length=100, verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='sensorlist',
            name='widget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scada.widget'),
        ),
    ]
