# Generated by Django 3.2.11 on 2022-06-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scada', '0013_auto_20220519_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWidgets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=150, verbose_name='Наименование')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.sensorlist')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
