# Generated by Django 3.2.11 on 2022-06-09 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0014_mywidgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
