# Generated by Django 3.2.11 on 2022-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0015_sensorlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywidgets',
            name='sort',
            field=models.IntegerField(default=9999, verbose_name='Индекс Сортировки'),
        ),
    ]
