# Generated by Django 3.2.11 on 2022-12-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0016_mywidgets_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorArhive',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data', models.IntegerField(blank=True, default=0, null=True, verbose_name='данные')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sensorId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scada.sensorlist')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scada.datatypes')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
                'ordering': ['-date'],
            },
        ),
    ]
