# Generated by Django 3.2.11 on 2023-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0017_sensorarhive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorarhive',
            options={'ordering': ['-date'], 'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='subtitle',
            field=models.CharField(default='-', max_length=10, verbose_name='Имя в датчике'),
        ),
    ]
