# Generated by Django 3.2.11 on 2023-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0018_auto_20230129_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlist',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
