# Generated by Django 3.2.11 on 2023-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0019_alter_sensorlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatypes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensorarhive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
