# Generated by Django 3.2.11 on 2024-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0020_auto_20230803_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlist',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Хратить историю'),
        ),
    ]
